#!/bin/bash

schema_install() {
  SCHEMA="$1"
  GCONF_CONFIG_SOURCE="xml::/usr/etc/gconf/gconf.xml.defaults" \
  gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/$SCHEMA
}

schema_install gnumeric-dialogs.schemas
schema_install gnumeric-general.schemas
schema_install gnumeric-plugins.schemas

update-desktop-database -q /usr/share/applications
gtk-update-icon-cache -f /usr/share/icons/hicolor
glib-compile-schemas /usr/share/glib-2.0/schemas
