if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

if [ -f /etc/profile.d/vte.sh ]; then
  source /etc/profile.d/vte.sh
fi

# Prefer my own freetype2 settings from the fonts-conf port
if [ -f /etc/profile.d/fonts-conf.sh ]; then
  source /etc/profile.d/fonts-conf.sh
fi

# If you have both qt5ct and qt6ct installed, qt5ct is enough
#if [ -f /etc/profile.d/qt6ct.sh ]; then
#  source /etc/profile.d/qt6ct.sh
#fi

if [ -f /etc/profile.d/qt5ct.sh ]; then
  source /etc/profile.d/qt5ct.sh
fi

# Disable hiding GTK3 scrollbars
if [ -f /etc/profile.d/bluecurve.sh ]; then
  source /etc/profile.d/bluecurve.sh
fi

## Locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8  # Uncomment if you need to force all categories
