## Use colour by default
alias ls="ls --color=auto"
alias ll="ls --color=auto -al"
alias cd..='cd ..'
alias ..='cd ..'

## I am not smart enough for vim
export VISUAL=nano
export EDITOR=nano

if [ -f /etc/profile.d/lscolors.sh ]; then
  source /etc/profile.d/lscolors.sh
fi
